import {Context as TelegrafContext} from "telegraf/typings/context";


interface Session {
  startDate: number;
  description: undefined | (Update.New & Update.NonChannel & Message.ChannelChatCreatedMessage) | (Update.New & Update.NonChannel & Message.ConnectedWebsiteMessage) | (Update.New & Update.NonChannel & Message.DeleteChatPhotoMessage) | (Update.New & Update.NonChannel & Message.GroupChatCreatedMessage) | (Update.New & Update.NonChannel & Message.InvoiceMessage) | (Update.New & Update.NonChannel & Message.LeftChatMemberMessage) | (Update.New & Update.NonChannel & Message.MessageAutoDeleteTimerChangedMessage) | (Update.New & Update.NonChannel & Message.MigrateFromChatIdMessage) | (Update.New & Update.NonChannel & Message.MigrateToChatIdMessage) | (Update.New & Update.NonChannel & Message.NewChatMembersMessage) | (Update.New & Update.NonChannel & Message.NewChatPhotoMessage) | (Update.New & Update.NonChannel & Message.NewChatTitleMessage) | (Update.New & Update.NonChannel & Message.PassportDataMessage) | (Update.New & Update.NonChannel & Message.ProximityAlertTriggeredMessage) | (Update.New & Update.NonChannel & Message.ForumTopicCreatedMessage) | (Update.New & Update.NonChannel & Message.ForumTopicClosedMessage) | (Update.New & Update.NonChannel & Message.ForumTopicReopenedMessage) | (Update.New & Update.NonChannel & Message.PinnedMessageMessage) | (Update.New & Update.NonChannel & Message.SuccessfulPaymentMessage) | (Update.New & Update.NonChannel & Message.SupergroupChatCreated) | (Update.New & Update.NonChannel & Message.VideoChatScheduledMessage) | (Update.New & Update.NonChannel & Message.VideoChatStartedMessage) | (Update.New & Update.NonChannel & Message.VideoChatEndedMessage) | (Update.New & Update.NonChannel & Message.VideoChatParticipantsInvitedMessage) | (Update.New & Update.NonChannel & Message.WebAppDataMessage) | (Update.New & Update.NonChannel & Message.AnimationMessage) | (Update.New & Update.NonChannel & Message.AudioMessage) | (Update.New & Update.NonChannel & Message.ContactMessage) | (Update.New & Update.NonChannel & Message.DiceMessage) | (Update.New & Update.NonChannel & Message.DocumentMessage) | (Update.New & Update.NonChannel & Message.GameMessage) | (Update.New & Update.NonChannel & Message.LocationMessage) | (Update.New & Update.NonChannel & Message.PhotoMessage) | (Update.New & Update.NonChannel & Message.PollMessage) | (Update.New & Update.NonChannel & Message.StickerMessage) | (Update.New & Update.NonChannel & Message.TextMessage) | (Update.New & Update.NonChannel & Message.VenueMessage) | (Update.New & Update.NonChannel & Message.VideoMessage) | (Update.New & Update.NonChannel & Message.VideoNoteMessage) | (Update.New & Update.NonChannel & Message.VoiceMessage);
  hour: number;
  sharing_to: "events" | "exhibitions" | "projects"
}

export default interface Context extends TelegrafContext {
  session: Session
}
